# Generated by Django 4.0.6 on 2022-08-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibros', '0004_alter_autor_options_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='publication_date',
            new_name='fecha_publicacion',
        ),
    ]
